name: Beta CICD

on:
  workflow_call:
  pull_request:
    types: [edited, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  BETA_SERVICE_NAME: ${{ github.head_ref }}-qa

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
